# Generated by Django 3.2.4 on 2021-07-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelIFBA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
