# Generated by Django 3.2.4 on 2021-06-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelIFBA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('dtNascimento', models.DateField()),
                ('endereço', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('idNumero', models.CharField(max_length=100)),
                ('idData', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='empresa',
            name='emai',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(max_length=250, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=11, null='True'),
            preserve_default='True',
        ),
    ]
