# Generated by Django 3.2.4 on 2021-06-21 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelIFBA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('dtNascimento', models.DateField()),
                ('telefone', models.CharField(max_length=100)),
                ('idNumero', models.CharField(max_length=100)),
                ('idData', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('senha', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=50)),
                ('numeroCartao', models.CharField(max_length=15)),
                ('agencia', models.CharField(max_length=6)),
                ('conta', models.CharField(max_length=6)),
                ('digito', models.IntegerField()),
                ('chavepix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroQuarto', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('interfoneNumero', models.IntegerField()),
                ('capacidade', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=11, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='qtdPessoas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataEntrada', models.DateTimeField()),
                ('dataSaida', models.DateTimeField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='HotelIFBA.cliente')),
                ('dadosPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadosPagamento', to='HotelIFBA.dadospagamento')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarto', to='HotelIFBA.quarto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelIFBA.endereco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelIFBA.endereco'),
        ),
    ]
