# Generated by Django 3.2.4 on 2021-06-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelIFBA', '0002_auto_20210618_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='emai',
            new_name='email',
        ),
    ]
