# Generated by Django 3.2.4 on 2021-06-19 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelIFBA', '0005_auto_20210618_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=50)),
                ('numeroCartao', models.CharField(max_length=15)),
                ('agencia', models.CharField(max_length=6)),
                ('conta', models.CharField(max_length=6)),
                ('digito', models.IntegerField()),
                ('chavepix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroQuarto', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('interfoneNumero', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataEntrada', models.DateTimeField()),
                ('dataSaida', models.DateTimeField()),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quarto', to='HotelIFBA.quarto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelIFBA.endereco'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelIFBA.endereco'),
        ),
    ]
