# Generated by Django 3.2.4 on 2021-06-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelIFBA', '0006_auto_20210619_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarto', to='HotelIFBA.quarto'),
        ),
    ]
